# Project: 项目1
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o others.o
LINKOBJ  = main.o others.o
LIBS     = -L"D:/工具/代码/Dev-Cpp/MinGW64/lib" -L"D:/工具/代码/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -g3
INCS     = -I"D:/工具/代码/Dev-Cpp/MinGW64/include" -I"D:/工具/代码/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/工具/代码/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/工具/代码/Dev-Cpp/MinGW64/include" -I"D:/工具/代码/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/工具/代码/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/工具/代码/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = 项目1.exe
CXXFLAGS = $(CXXINCS) -std=c++0x
CFLAGS   = $(INCS) -std=c++0x
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

others.o: others.cpp
	$(CPP) -c others.cpp -o others.o $(CXXFLAGS)
